Benchmarking
seL4/microkit pull request #11
Opened 2022-08-19 02:59 UTC by lucypa

This PR enables users to specify a 'benchmark' config in order to use seL4's benchmarking system calls.

2023-02-26 23:47 UTC, bennoleslie requested changes
Overall need to think about how we have benchmarking builds and changes.

Code is very good, no issues there. We just need to think about bigger picture.
I really don't like the idea of requiring different builds for benchmarking vs production. 

I think it leads to potential (unintentional) cheating / fooling ourselves by having potential different code running for benchmarks vs production, which I think we should be able to find a good alternative to.

More general comments: with an MR please try to make the MR title a bit longer than just "Benchmarking", and then provide a bit more detail in the MR description.

for example here it could be something like:

"Add support to enable system benchmarking"

and the description would be something like:

> Add a benchmark kernel that includes xxxx so that yyyy.
> Add TCB cap to PD to enable the code to call xxx so that we get benchmark yyyy.

We should also update the manual appropriately as well.

Let's get the passive server MR complete first, and then rebase this branch off master once the passive server change is merged.

(And apologies, this is my fault for not being able to review in a more timely manner).

2023-02-26 23:47 UTC, bennoleslie commented on tool/sel4coreplat/__main__.py
> +    # Copy the PD's TCB cap into their address space for development purposes.
I *think* that this is only needed for development purposes, and following POLA we'd ideally avoid having this cap available in production.

We probably need to think about the best way to support development cap needs vs production cap needs. Could be topic for a Monday meeting discussion. I'll think some more about it.

2023-02-26 23:47 UTC, bennoleslie commented on build_sdk.py
> +    )
Let's avoid unrelated changes. In this case the trailing comma was intentional.

What we will do here in future is use: https://black.readthedocs.io/en/stable/index.html to auto-format all the Python code, which should avoid any of these issues.

2023-03-05 22:41 UTC, bennoleslie commented
Please review conflicts (ideally rebase from master and push)

2024-07-03 06:09 UTC, Ivan-Velickovic commented
Re-done this work in https://github.com/seL4/microkit/pull/157 since lots has changed since this PR.

2024-07-03 06:09 UTC, closed without merging